# Generated by Django 2.1 on 2018-09-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='name',
            new_name='nome',
        ),
    ]
