# Generated by Django 2.1.2 on 2018-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20180927_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
            },
        ),
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
                ('depoimento', models.CharField(max_length=900)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
                ('agencia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Psicologo',
                'verbose_name_plural': 'Psicologos',
            },
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='livros',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
